image: node:lts-hydrogen

stages:
  - build
  - test
  - deploy

cache:
  key:
    files:
      - yarn.lock
  paths:
    - .yarn/cache

variables:
  SERVER_IP: "$SERVER_IP"
  SSH_PRIVATE_KEY: "$SSH_PRIVATE_KEY"

.before_script_template: &deploy_run-docker
  before_script:
    - set -e
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - mkdir -p ~/.ssh
    - touch ~/.ssh/config
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" >> ~/.ssh/config

build_react:
  tags:
    - test
  stage: build
  script:
    - yarn install
    - yarn lint
    - yarn build

test_react:
  tags:
    - test
  stage: test
  script:
    - yarn install
    - yarn test --maxWorkers=2

docker_build_main:
  # Official docker image.
  image: docker:latest
  stage: deploy
  services:
    - docker:dind
  tags:
    - gitlab-org
  before_script:
    - docker login -u "$DOCKER_HUB_USERNAME" -p "$DOCKER_HUB_PASSWORD" $DOCKER_HUB_URL
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE" .
    - docker push "$CI_REGISTRY_IMAGE"
  only:
    - main

docker_build_other:
  # Official docker image.
  image: docker:latest
  stage: deploy
  services:
    - docker:dind
  tags:
    - gitlab-org
  before_script:
    - docker login -u "$DOCKER_HUB_USERNAME" -p "$DOCKER_HUB_PASSWORD" $DOCKER_HUB_URL
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG" .
    - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG"
  except:
    - main

deploy:
  tags:
   - dev
  stage: deploy
  <<: *deploy_run-docker
  script:
   - 'ssh "$SERVER_IP" /root/gitlab-deploy.sh'
  only:
   - development
