image: node:lts-hydrogen

stages:
  - build
  - test
  - staging
  - deploy

cache:
  key:
    files:
      - yarn.lock
  paths:
    - node_modules/

variables:
  SERVER_IP: "$SERVER_IP"
  SSH_PRIVATE_KEY: "$SSH_PRIVATE_KEY"

.before_script_template: &deploy_run-docker
  before_script:
    - set -e
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - mkdir -p ~/.ssh
    - touch ~/.ssh/config
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" >> ~/.ssh/config

build_react:
  tags:
    - docker
  stage: build
  script:
    - yarn install
    - yarn build

test:
  tags:
    - docker
  stage: test
  script:
    - yarn test --maxWorkers=2

deploy:
  tags:
   - dev
  stage: deploy
  <<: *deploy_run-docker
  script:
   - 'ssh "$SERVER_IP" /root/gitlab-deploy.sh'
  only:
   - development

build_docker:
  image: docker:20.10.16
  stage: staging
  services:
    - docker:20.10.16-dind
  variables:
    IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  script:
    - docker login -u $CI_DOCKER_HUB_USERNAME -p $CI_DOCKER_HUB_PASSWORD docker.io
    - docker build -t $IMAGE_TAG .
    - docker push $IMAGE_TAG

