version: "3.7"

services:
  catalog-front:
    build:
      context: ./
      target: prod
    working_dir: /app
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    ports:
      - "3002:3002"
    command: yarn start
volumes:
  node_modules: