version: "3.7"

services:
  catalog-front:
    build:
      context: ./
      target: prod
    working_dir: /app
    user: nextjs
    stdin_open: true
    ports:
      - "3002:3002"
    command: yarn start
