version: "3.7"
services:
  web:
    build:
      context: ../../../product-registry
      target: build-web
    entrypoint: /t4d/docker-entrypoint.sh
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - ../../../product-registry:/t4d
      - ../../../product-registry/prod/logrotate.d/registry:/etc/logrotate.d/registry
    network_mode: host
    env_file: .env

  catalog-front:
    build:
      context: ../..
      target: prod
    working_dir: /app
    user: nextjs
    stdin_open: true
    command: yarn start
    network_mode: host
    env_file: .env

  db:
    image: postgres:12
    network_mode: host
    environment:
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_HOST=${DATABASE_HOST}
      - POSTGRES_PORT=${DATABASE_PORT}
      - POSTGRES_DB=${DATABASE_NAME}

  redis:
    image: redis
    command: "--requirepass ${REDIS_PASSWORD} --port ${REDIS_PORT}"
    network_mode: host
    env_file: .env
